version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: grande-midia-db-dev
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=grande_midia
      - POSTGRES_PASSWORD=senha_local
      - POSTGRES_DB=grande_midia_mt
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

volumes:
  pgdata_dev: